esphome:
  name: esp-garage-door
  friendly_name: ESP Garage Door

packages:
  common: !include ../common.yaml

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key_garage_door

ota:
  - platform: esphome
    password: !secret ota_password_garage_door

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Garage-Door Fallback Hotspot"
    password: !secret ap_password_garage_door

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO18
      inverted: true
      mode:
        input: true
        pullup: true    
    id: door_closed
    name: "Door Closed"
    filters:
      - delayed_on_off:
          time_on: 2000ms
          time_off: 1000ms
    on_release: 
      - light.turn_on: statusled
      - binary_sensor.template.publish:
          id: door_opening
          state: ON
    on_press:
      - light.turn_off: statusled
      - binary_sensor.template.publish:
          id: door_closing
          state: OFF
      - binary_sensor.template.publish:
          id: door_opening
          state: OFF
  - platform: gpio
    pin:
      number: GPIO21
      inverted: true
      mode:
        input: true
        pullup: true    
    id: door_open
    name: "Door Open"
    filters:
      - delayed_on_off:
          time_on: 4000ms
          time_off: 2000ms
    on_release: 
      - binary_sensor.template.publish:
          id: door_closing
          state: ON
    on_press:
      - binary_sensor.template.publish:
          id: door_closing
          state: OFF
      - binary_sensor.template.publish:
          id: door_opening
          state: OFF
  - platform: template
    id: door_opening
    name: "Door Opening"
  - platform: template
    id: door_closing
    name: "Door Closing"

switch:
  - platform: gpio
    pin: GPIO19
    id: door_drive
    name: "Trigger Door"
    internal: false
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: door_drive

cover:
  - platform: template
    id: garage_door
    device_class: garage
    name: "Garage Door"
    lambda: |-
      if (id(door_closed).state) {
        return COVER_CLOSED;
      }
      else {
        return COVER_OPEN;
      }
    open_action:
      switch.turn_on: door_drive
    close_action:
      switch.turn_on: door_drive
    stop_action:
      switch.turn_on: door_drive

