esphome:
  name: esp-mailbox
  friendly_name: ESP Mailbox

packages:
  common: !include ../common.yaml

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key_mailbox

ota:
  - platform: esphome
    password: !secret ota_password_mailbox

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Mailbox Fallback Hotspot"
    password: !secret ap_password_mailbox

light:
  - platform: monochromatic
    output: ambient_light
    default_transition_length: 60000ms
    name: "Ambient Light"

number:
  - platform: template
    id: dropped
    name: "Mail Items"
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true
    on_value: 
      then:
        - if:
            condition: 
              lambda: 'return id(dropped).state > 0;'
            then:
              - binary_sensor.template.publish:
                  id: loaded
                  state: true
            else:
              - binary_sensor.template.publish:
                  id: loaded
                  state: false

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO23
      inverted: false
      mode:
        input: true
        pullup: true    
    id: slot
    name: "Slot"
    filters:
      - delayed_on_off:
          time_on: 100ms
          time_off: 100ms
    on_press: 
      - script.execute: slot_open_script
  - platform: gpio
    pin:
      number: GPIO18
      inverted: false
      mode:
        input: true
        pullup: true    
    id: flap
    name: "Flap"
    filters:
      - delayed_on_off:
          time_on: 100ms
          time_off: 100ms
    on_press: 
      - binary_sensor.template.publish:
          id: flap_opened
          state: true
      - number.to_min: dropped
    on_release: 
      - script.execute: flap_close_script
  - platform: template
    id: flap_opened
    internal: true
    name: "Flap Opened"
  - platform: template
    id: loaded
    name: "Mail Delivered"
    on_press:
      - light.turn_on: statusled
    on_release: 
      - light.turn_off: statusled

button:
  - platform: template
    name: "Reset"
    id: load_reset
    icon: "mdi:delete-restore"
    on_press:
      - number.to_min: dropped

output:
  - platform: ledc
    pin: GPIO13
    id: ambient_light

script:
  - id: slot_open_script
    mode: restart
    then:
      - delay: 10s
      - if:
          condition: 
            lambda: 'return id(flap_opened).state == false;'
          then:
            - number.increment: dropped
  - id: flap_close_script
    mode: restart
    then:
      - delay: 10s
      - binary_sensor.template.publish:
          id: flap_opened
          state: false      
